export enum RecordStatus {
  DRAFT = 'DRAFT',
  SAVED = 'SAVED',
  SEALED = 'SEALED',
  UNLOCKED = 'UNLOCKED',
}

export enum RecordType {
  MOMENT = 'MOMENT',
  FUTURE_LETTER = 'FUTURE_LETTER',
  NODE_RECORD = 'NODE_RECORD',
  EMOTION_NOTE = 'EMOTION_NOTE',
}

export enum LifeNodeType {
  GRADUATION = 'GRADUATION',
  WORK = 'WORK',
  MOVE = 'MOVE',
  RELATIONSHIP = 'RELATIONSHIP',
  HEALTH = 'HEALTH',
  FAMILY = 'FAMILY',
  TURNING_POINT = 'TURNING_POINT',
  OTHER = 'OTHER',
}

export enum TagType {
  MOOD = 'MOOD',
  TOPIC = 'TOPIC',
}

export enum ReplyType {
  SHORT_REPLY = 'SHORT_REPLY',
}

export enum RecordReminderStatus {
  REQUESTED = 'REQUESTED',
  AUTHORIZED = 'AUTHORIZED',
  DENIED = 'DENIED',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  SEND_PENDING = 'SEND_PENDING',
  SEND_SUCCESS = 'SEND_SUCCESS',
  SEND_FAILED = 'SEND_FAILED',
  SKIPPED_NO_OPENID = 'SKIPPED_NO_OPENID',
}
