package com.flashback.domain;

public enum DataOperationFailureCode {
    AUTHORIZATION_CHANGED,
    OPERATION_CONFLICT,
    SNAPSHOT_CHANGED,
    REMOTE_OBJECT_DELETE_FAILED,
    REMOTE_OBJECT_READ_FAILED,
    DATABASE_DELETE_FAILED,
    DERIVED_DATA_REMAINS,
    ARTIFACT_BUILD_FAILED,
    ARTIFACT_EXPIRED,
    LOCAL_STORAGE_UNAVAILABLE,
    INVARIANT_VIOLATION
}
